# Generated by Django 5.2.8 on 2025-11-25 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('anomaly_type', models.CharField(choices=[('irrigation', 'irrigation'), ('temperature', 'temperature'), ('humidity', 'humidity'), ('other', 'other')], max_length=50)),
                ('severity', models.FloatField(blank=True, null=True)),
                ('model_confidence', models.FloatField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='AgentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recommended_action', models.TextField()),
                ('explanation_text', models.TextField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('anomaly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='monitoring.anomalyevent')),
            ],
        ),
        migrations.CreateModel(
            name='FarmProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('size', models.FloatField(blank=True, null=True)),
                ('crop_type', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('crop_variety', models.CharField(blank=True, max_length=100, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='monitoring.farmprofile')),
            ],
        ),
        migrations.AddField(
            model_name='anomalyevent',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='monitoring.fieldplot'),
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('sensor_type', models.CharField(choices=[('moisture', 'moisture'), ('temperature', 'temperature'), ('humidity', 'humidity')], max_length=30)),
                ('value', models.FloatField()),
                ('source', models.CharField(default='simulator', max_length=100)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='monitoring.fieldplot')),
            ],
        ),
    ]
